players_name = input("Please, enter your name: ")
team_name = input("Enter team name: ")
player_position = input("Enter player position: ")
jersey_number = input("Enter jersey number: ")
Hometown = input("Enter Hometown: ")
print("########################################")
print("       LEGENDS OF THE LEAGUE")
print("########################################")
print()
print("Player:   " + players_name)
print("Team:     " + team_name)
print("Position: " + player_position)
print("Number:   " + jersey_number)
print()
print("----------------------------------------")
print("player tag:    " + jersey_number + '-'+team_name +'-'+players_name)
print("Hometown:      " + Hometown)
print("----------------------------------------")
print("########################################")
